# Dev-QA-Prod-Parallel-azure-pipeline
#     dependsOn: [] #this removes the dependency on previous stage

trigger:
 - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Dev
    jobs:
      - job: Dev_Job
    
  - stage: QA-Team_1
    dependsOn: Dev
    jobs:
      - job: QA_Job

  - stage: QA-Team_2
    dependsOn: Dev
    jobs:
        - job: QA_Job
    
  - stage: Prod
    dependsOn:
    jobs:
      - job: Pord_Job

