# Dev-QA-Prod-Parallel-azure-pipeline
#     dependsOn: [] #this removes the dependency on previous stage

trigger:
 - main



stages:
  - stage: Dev
    pool: 
      vmImage: ubuntu-latest
    jobs:
      - job: Dev_Job
    
  - stage: QA_Team_1
    dependsOn: []
    jobs:
      - job: QA_Job

  - stage: QA_Team_2
    dependsOn: []
    jobs:
        - job: QA_Job
    pool: 
      vmImage: windows-latest
    
  - stage: Prod 
    dependsOn:
      - QA_Team_1
      - QA_Team_2
    jobs:
      - job: Pord_Job

