# Dev-QA-Prod-Parallel-azure-pipeline

trigger:
 - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Dev
    jobs:
      - job: Dev_Job
    
  - stage: QA
    dependsOn: [] #this removes the dependency on previous stage 
    jobs:
      - job: QA_Job
    
  - stage: Prod
    dependsOn: [] #this removes the dependency on previous stage 
    jobs:
      - job: Pord_Job

