# Dev-QA-Prod-azure-pipeline Practise

trigger:
 - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Dev
    jobs:
      - job: Dev_Job
    
  - stage: QA
    jobs:
      - job: QA_Job
    
  - stage: Prod
    dependsOn: Dev
    jobs:
      - job: Pord_Job

