# Dev-QA-Prod-Parallel-azure-pipeline
#     dependsOn: [] #this removes the dependency on previous stage

trigger:
 - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Dev
    jobs:
      - job: Dev_Job
    
  - stage: QA_Team_1
    dependsOn: Dev
    jobs:
      - job: QA_Job

  - stage: QA_Team_2
    dependsOn: Dev
    jobs:
        - job: QA_Job
    
  - stage: Prod
    dependsOn:
      - QA_Team_1
      - QA_Team_2
    jobs:
      - job: Pord_Job

